package com.ecommerce.quality.real;

import static org.junit.jupiter.api.Assertions.*;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import java.nio.charset.StandardCharsets;
import org.junit.jupiter.api.Test;

class RealEventCodecTest {
    // Synthetic contract vectors generated by the existing Python normalizer, not demonstration data.
    static final String BASIC = """
        {"event_time":"2019-10-01T00:00:00+00:00","event_type":"view",
         "product_id":"100000000000000001","category_id":null,"category_code":null,
         "brand":null,"price":"12.30","user_id":"000123","user_session":null,
         "schema_version":1,"event_id":"real_81e8826e2007694fc42851e3070c38549823cf8f16ce5b0f7bc7bd306eb56fc2",
         "dataset_id":"rees46-multicategory-2019-2020","source_file":"2019-Oct.csv.gz",
         "source_row_number":1,"replay_schema_version":1,
         "replay_id":"11111111-1111-4111-8111-111111111111","replayed_at":"2026-09-18T00:00:00+00:00"}
        """;
    private final ObjectMapper mapper = new ObjectMapper();
    private final RealEventCodec codec = new RealEventCodec();

    static KafkaEnvelope envelope(String value) {
        return new KafkaEnvelope("real_behavior_events_v1_test", 2, 37L,
                value == null ? null : value.getBytes(StandardCharsets.UTF_8));
    }

    @Test
    void preservesAllSeventeenFieldsAndKafkaIdentity() throws Exception {
        RealEvent event = codec.parse(envelope(BASIC));
        assertEquals(mapper.readTree(BASIC), mapper.readTree(event.json));
        assertEquals(17, mapper.readTree(event.json).size());
        assertEquals("000123", event.userId);
        assertEquals(1569888000000L, event.eventTimeMillis);
        assertEquals(2, event.partition);
        assertEquals(37L, event.offset);
        assertEquals(envelope(BASIC).topic, event.topic);
    }

    @Test
    void agreesWithPythonForUnicodeNullEscapesMaximumPriceAndLongOrdinal() throws Exception {
        ObjectNode input = (ObjectNode) mapper.readTree(BASIC);
        input.put("brand", "\u54c1\u724c\ud83d\ude00");
        input.put("category_code", "x\\y\"z");
        input.put("price", "999999999999999999.99");
        input.put("event_type", "remove_from_cart");
        input.put("source_row_number", Long.MAX_VALUE);
        input.put("event_id", "real_55873de02b64fb9274810fdb98bbbc2cfd96b30608ca64bebda4017103cace15");
        assertEquals(input, mapper.readTree(codec.parse(envelope(input.toString())).json));
    }

    @Test
    void rejectsNonCanonicalFieldsBeforeAcceptingIdentity() throws Exception {
        String[][] invalid = {
            {"event_type", "pay", "INVALID_EVENT_TYPE"},
            {"price", "12.3", "INVALID_PRICE"},
            {"price", "01.00", "INVALID_PRICE"},
            {"price", "-1.00", "INVALID_PRICE"},
            {"event_time", "2019-02-30T00:00:00+00:00", "INVALID_EVENT_TIME"},
            {"event_time", "2019-10-01T00:00:00Z", "INVALID_EVENT_TIME"},
            {"source_file", "2019-Nov.csv.gz", "INVALID_SOURCE"},
            {"dataset_id", "unknown", "INVALID_SOURCE"},
            {"user_id", "\u00a0user", "INVALID_FIELD"},
            {"brand", "", "INVALID_FIELD"},
            {"event_id", "real_" + "0".repeat(64), "INVALID_EVENT_ID"},
            {"replayed_at", "2026-09-18T08:00:00+08:00", "INVALID_REPLAY_METADATA"},
            {"replay_id", "not-a-uuid", "INVALID_REPLAY_METADATA"}
        };
        for (String[] example : invalid) {
            ObjectNode input = (ObjectNode) mapper.readTree(BASIC);
            input.put(example[0], example[1]);
            assertReason(example[2], input.toString());
        }
        ObjectNode input = (ObjectNode) mapper.readTree(BASIC);
        input.put("user_id", 123);
        assertReason("INVALID_FIELD", input.toString());
        input = (ObjectNode) mapper.readTree(BASIC);
        input.put("source_row_number", 1.0);
        assertReason("INVALID_SOURCE", input.toString());
        input.put("source_row_number", 0);
        assertReason("INVALID_SOURCE", input.toString());
        input = (ObjectNode) mapper.readTree(BASIC);
        input.put("schema_version", 1.0);
        assertReason("INVALID_VERSION", input.toString());
        input.put("schema_version", 2);
        assertReason("INVALID_VERSION", input.toString());
    }

    @Test
    void rejectsMalformedUnknownMissingDuplicateTrailingAndOversizedJson() throws Exception {
        for (String value : new String[] {"{bad", "[]", "null", BASIC + " {}",
                BASIC.replace("\"price\":\"12.30\"", "\"price\":\"12.30\",\"price\":\"12.30\"")}) {
            assertReason("MALFORMED_JSON", value);
        }
        ObjectNode input = (ObjectNode) mapper.readTree(BASIC);
        input.put("channel", "fake");
        assertReason("INVALID_FIELDS", input.toString());
        input.remove("channel");
        input.remove("brand");
        assertReason("INVALID_FIELDS", input.toString());
        assertReason("MALFORMED_JSON", null);
        assertReason("MESSAGE_TOO_LARGE", "x".repeat(65537));
        KafkaEnvelope invalidUtf8 = new KafkaEnvelope("test", 0, 0, new byte[] {(byte) 0xc3, 0x28});
        assertEquals("INVALID_UTF8", assertThrows(RealEventCodec.InvalidEvent.class,
                () -> codec.parse(invalidUtf8)).code());
    }

    @Test
    void rejectionIsBoundedAndRetainsCoordinatesAndKnownIdentity() throws Exception {
        JsonNode invalid = mapper.readTree(codec.rejection(envelope("x".repeat(70000)), "MESSAGE_TOO_LARGE"));
        assertEquals(37, invalid.get("source_offset").asLong());
        assertEquals(2, invalid.get("source_partition").asInt());
        assertEquals(2048, invalid.get("raw_preview").asText().length());
        assertTrue(invalid.get("raw_truncated").asBoolean());
        assertEquals(70000, invalid.get("raw_bytes").asLong());
        assertEquals(64, invalid.get("raw_sha256").asText().length());
        JsonNode duplicate = mapper.readTree(codec.rejection(envelope(BASIC), "DUPLICATE_EVENT"));
        assertEquals(mapper.readTree(BASIC).get("event_id"), duplicate.get("event_id"));
        assertEquals(mapper.readTree(BASIC).get("replay_id"), duplicate.get("replay_id"));
        assertTrue(mapper.readTree(codec.rejection(envelope(null), "MALFORMED_JSON"))
                .get("raw_is_null").asBoolean());
    }

    @Test
    void acceptsExactByteLimitAndRejectsTheNextByte() {
        String exact = BASIC + " ".repeat(65536 - BASIC.getBytes(StandardCharsets.UTF_8).length);
        assertEquals(65536, codec.parse(envelope(exact)).json.getBytes(StandardCharsets.UTF_8).length);
        assertReason("MESSAGE_TOO_LARGE", exact + " ");
    }

    @Test
    void countsUnicodeCodePointsAndTruncatesDiagnosticsWithoutSplittingSurrogates() throws Exception {
        ObjectNode input = (ObjectNode) mapper.readTree(BASIC);
        input.put("brand", "\ud83d\ude00".repeat(512));
        input.put("event_id", "real_efafe475c8ea1866734e2cae5bcc76b0dce41736a0b6f97ce5d3e0bed4538e52");
        assertEquals(input, mapper.readTree(codec.parse(envelope(input.toString())).json));
        input.put("brand", "\ud83d\ude00".repeat(513));
        assertReason("INVALID_FIELD", input.toString());
        JsonNode report = mapper.readTree(codec.rejection(envelope("\ud83d\ude00".repeat(3000)), "MALFORMED_JSON"));
        String preview = report.get("raw_preview").asText();
        assertEquals("\ud83d\ude00".repeat(2048), preview);
        assertTrue(report.get("raw_truncated").asBoolean());
    }

    private void assertReason(String reason, String value) {
        assertEquals(reason, assertThrows(RealEventCodec.InvalidEvent.class,
                () -> codec.parse(envelope(value))).code(), reason);
    }
}
